<?php

return [
    "Home" => [
        "label" => 'Home',
        "module" => "Application",
        "ruote" => "home",
        "controller" => "index",
        "action" => "index",
        "resource" => Application\Controller\IndexController::class,
        "permission" => "Application_index",
        "parent" => "",
        "params" => "",
        "query" => "",
        "class" => "",
        "icon" => "",
        "sort" => 1
    ],
    "UserProfile" => [
        "label" => 'Login',
        "module" => "CostAuthentication",
        "ruote" => "cost-auth/default",
        "controller" => "index",
        "action" => "index",
        "resource" => CostAuthentication\Controller\IndexController::class,
        "permission" => "CostAuthentication_Login",
        "parent" => "",
        "params" => "",
        "query" => "",
        "class" => "",
        "icon" => "",
        "sort" => 1
    ],
    "LogOut" => [
        "label" => 'Logout',
        "module" => "CostAuthentication",
        "ruote" => "logout",
        "controller" => "index",
        "action" => "logout",
        "resource" => CostAuthentication\Controller\IndexController::class,
        "permission" => "CostAuthentication_Logout",
        "parent" => "",
        "params" => "",
        "query" => "",
        "class" => "",
        "icon" => "",
        "sort" => 1
    ],
    "UserProfile" => [
        "label" => 'Profilo Utente',
        "module" => "CostAuthentication",
        "ruote" => "user",
        "controller" => "index",
        "action" => "index",
        "resource" => CostAuthentication\Controller\IndexController::class,
        "permission" => "CostAuthentication_Register_Edit",
        "parent" => "",
        "params" => "",
        "query" => "",
        "class" => "",
        "icon" => "",
        "sort" => 1
    ],
    "Admin" => [
        "label" => 'Admin',
        "module" => "CostAdmin",
        "ruote" => "admin-application",
        "controller" => "index",
        "action" => "index",
        "resource" => CostAdmin\Controller\IndexController::class,
        "permission" => "Cost_admin_dashboard",
        "parent" => "",
        "params" => "",
        "query" => "",
        "class" => "",
        "icon" => "",
        "sort" => 1
    ],
    "Admin_anag_resource" => [
        "label" => 'Resource',
        "module" => "CostAdmin",
        "ruote" => "admin-resource",
        "controller" => "index",
        "action" => "resource",
        "resource" => CostAdmin\Controller\IndexController::class,
        "permission" => "Cost_admin_dashboard",
        "parent" => "Admin",
        "params" => "",
        "query" => "",
        "class" => "",
        "icon" => "",
        "sort" => 2
    ],
    "Admin_anag_role" => [
        "label" => 'Role',
        "module" => "CostAdmin",
        "ruote" => "admin-role",
        "controller" => "index",
        "action" => "role",
        "resource" => CostAdmin\Controller\IndexController::class,
        "permission" => "Cost_admin_dashboard",
        "parent" => "Admin",
        "params" => "",
        "query" => "",
        "class" => "",
        "icon" => "",
        "sort" => 3
    ],
    "Admin_anag_permission" => [
        "label" => 'Permission',
        "module" => "CostAdmin",
        "ruote" => "admin-permission",
        "controller" => "index",
        "action" => "permission",
        "resource" => CostAdmin\Controller\IndexController::class,
        "permission" => "Cost_admin_dashboard",
        "parent" => "Admin",
        "params" => "",
        "query" => "",
        "class" => "",
        "icon" => "",
        "sort" => 4
    ],
    "Admin_anag_user" => [
        "label" => 'User',
        "module" => "CostAdmin",
        "ruote" => "admin-user",
        "controller" => "index",
        "action" => "user",
        "resource" => CostAdmin\Controller\IndexController::class,
        "permission" => "Cost_admin_dashboard",
        "parent" => "Admin",
        "params" => "",
        "query" => "",
        "class" => "",
        "icon" => "",
        "sort" => 5
    ],
    "Admin_anag_menu" => [
        "label" => 'Menu',
        "module" => "CostAdmin",
        "ruote" => "admin-menu",
        "controller" => "index",
        "action" => "menu",
        "resource" => CostAdmin\Controller\IndexController::class,
        "permission" => "Cost_admin_dashboard",
        "parent" => "Admin",
        "params" => "",
        "query" => "",
        "class" => "",
        "icon" => "",
        "sort" => 6
    ],
    "Admin_anag_translation" => [
        "label" => 'Translation',
        "module" => "CostAdmin",
        "ruote" => "admin-translation",
        "controller" => "index",
        "action" => "translation",
        "resource" => CostAdmin\Controller\IndexController::class,
        "permission" => "Cost_admin_dashboard",
        "parent" => "Admin",
        "params" => "",
        "query" => "",
        "class" => "",
        "icon" => "",
        "sort" => 7
    ]
];


